### ISSUE TITLE
Define & setup application infrastructure 

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v33-bears-team-10#17]
**__Feature Description__**
Define & setup the application infrastructure to prepare for the start of development activities.

**__Major User Stories/tasks__**
- [x] Identify FE & BE technical stacks
- [x] Setup FE application architecture
- [x] Setup BE application architecture

**__Additional Considerations__**
- It's okay to set stretch goals by including technologies unfamiliar to the team, but these should not be more than 25% of the overall technical stack

**Comment by jdmedlock** [comment]
A review of the [Team Directory](https://docs.google.com/spreadsheets/d/1AKhjjq9UbVFuQJQ8aPcUIHhdFdXV3vWc/edit?usp=sharing&ouid=103300881827413139686&rtpof=true&sd=true) show these common technologies & libraries:

**__FE__**                       **__BE__**
Javascript                         Python
React                                  Node/Express
                                             Django
                                             PostgreSQL
